name: Athena CAP Validation & Ledger Commit

on:
  workflow_dispatch:
    inputs:
      cap_payload:
        description: "CAP JSON payload (paste the inner object here)"
        required: true
        default: |
          {
            "cap_id": "test-001",
            "timestamp": "2025-10-29T00:00:00Z",
            "domain": "Governance",
            "context_mode": "Advisor",
            "hs": 0.88,
            "hci": 0.74,
            "haa": 0.91,
            "reasoning_summary": "Manual CAP validation test via UI.",
            "status": "pending"
          }

permissions:
  contents: write

env:
  SCHEMA_PATH: "./schemas/ATHENA_CAP_SCHEMA_v3_4.json"
  LEDGER_PATH: "./CAP_LOGS"
  SCHEMA_VERSION: "v3.4"

jobs:
  validate_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare CAP_LOGS directory
        run: mkdir -p $LEDGER_PATH

      - name: Normalize CAP payload
        run: |
          echo "${{ github.event.inputs.cap_payload }}" > raw_payload.txt
          # Try to parse; if it fails (means input was quoted), unwrap it
          if ! jq empty raw_payload.txt 2>/dev/null; then
            echo "Unwrapping quoted input..."
            cat raw_payload.txt | jq -R 'fromjson' > cap_payload.json
          else
            mv raw_payload.txt cap_payload.json
          fi
          echo "=== CAP payload written ==="
          cat cap_payload.json

      - name: Debug Schema Header
        run: |
          echo "=== Printing first 10 lines of schema file ($SCHEMA_PATH) ==="
          head -n 10 $SCHEMA_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Validate CAP JSON (Node/AJV 2020)
        run: |
          cat <<'EOF' > validate.js
          const fs = require('fs');
          const Ajv2020 = require('ajv/dist/2020');
          const addFormats = require('ajv-formats');
          const schema = JSON.parse(fs.readFileSync(process.env.SCHEMA_PATH));
          const data = JSON.parse(fs.readFileSync('cap_payload.json'));
          const ajv = new Ajv2020({ strict: false, allErrors: true });
          addFormats(ajv);
          const validate = ajv.compile(schema);
          const valid = validate(data);
          if (!valid) {
            console.error('❌ Validation errors:', validate.errors);
            process.exit(1);
          } else {
            console.log('✅ CAP JSON validated successfully.');
          }
          EOF
          npm install ajv@8 ajv-formats@2
          node validate.js

      - name: Generate CAP filename and hash
        id: hash_gen
        run: |
          TIMESTAMP=$(jq -r '.timestamp' cap_payload.json | tr -d '":')
          CAP_ID=$(jq -r '.cap_id' cap_payload.json)
          DOMAIN=$(jq -r '.domain' cap_payload.json | tr '[:upper:]' '[:lower:]')
          YEAR=$(date -u +"%Y")
          MONTH=$(date -u +"%m")
          FILEPATH="$LEDGER_PATH/$YEAR/$MONTH/${DOMAIN}_${CAP_ID}.json"
          mkdir -p $(dirname "$FILEPATH")
          SHA256=$(sha256sum cap_payload.json | awk '{print $1}')
          echo "file=$FILEPATH" >> $GITHUB_OUTPUT
          echo "hash=$SHA256" >> $GITHUB_OUTPUT
          echo "Generated hash: $SHA256"

      - name: Commit CAP record to ledger
        run: |
          FILE=${{ steps.hash_gen.outputs.file }}
          mkdir -p $(dirname "$FILE")
          cp cap_payload.json "$FILE"
          git config user.name "Athena-Audit-Bot"
          git config user.email "audit-bot@falconforge.ai"
          git add "$FILE"
          git commit -m "Add CAP record: ${{ github.event.inputs.cap_payload.cap_id }} [${{ steps.hash_gen.outputs.hash }}]"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Output validation summary
        run: |
          echo "✅ CAP record committed successfully."
          echo "Schema Version: $SCHEMA_VERSION"
          echo "Record Hash: ${{ steps.hash_gen.outputs.hash }}"
